export const genreOrigins = {
  "thai pop": "Thailand",
  "t-pop": "Thailand",
  "thai rock": "Thailand",
  "city pop": "Japan",
  "j-pop": "Japan",
  "j-rock": "Japan",
  "visual kei": "Japan",
  "enka": "Japan",
  "anime": "Japan",
  "jazz": "USA",
  "jazz fusion": "USA",
  "blues": "USA",
  "rock": "USA",
  "hip hop": "USA",
  "country": "USA",
  "folk": "USA",
  "bluegrass": "USA",
  "gospel": "USA",
  "funk": "USA",
  "soul": "USA",
  "r&b": "USA",
  "pop": "USA",
  "k-pop": "South Korea",
  "k-ballad": "South Korea",
  "k-indie": "South Korea",
  "mandopop": "China",
  "c-pop": "China",
  "cantopop": "Hong Kong",
  "bossa nova": "Brazil",
  "samba": "Brazil",
  "afrobeat": "Nigeria",
  "afrobeats": "Nigeria",
  "highlife": "Ghana",
  "soukous": "Congo (Kinshasa)",
  "classical": "Germany",
  "baroque": "Italy",
  "romantic": "Austria",
  "waltz": "Austria",
  "reggaeton": "Puerto Rico",
  "latin pop": "Mexico",
  "ranchera": "Mexico",
  "flamenco": "Spain",
  "fado": "Portugal",
  "french pop": "France",
  "chanson": "France",
  "italian opera": "Italy",
  "arab pop": "Egypt",
  "rai": "Algeria",
  "indian classical": "India",
  "bollywood": "India",
  "bhajan": "India",
  "punjabi": "India",
  "desi hip hop": "India",
  "indie": "UK",
  "britpop": "UK",
  "grime": "UK",
  "dubstep": "UK",
  "drum and bass": "UK",
  "techno": "Germany",
  "trance": "Germany",
  "house": "USA",
  "deep house": "USA",
  "ambient": "UK",
  "synthpop": "UK",
  "new wave": "UK",
  "eurodance": "Germany",
  "schlager": "Germany",
  "celtic": "Ireland",
  "tango": "Argentina",
  "vallenato": "Colombia",
  "cumbia": "Colombia",
  "salsa": "Cuba",
  "son cubano": "Cuba",
  "kizomba": "Angola",
  "zouk": "Guadeloupe",
  "jungle": "UK"
};
